// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPU22XgGDCkQVB4CLXpTwDf_vZKw76IOA',
    appId: '1:167961728502:web:e0a3b70213999d68f2a3d7',
    messagingSenderId: '167961728502',
    projectId: 'to-do-app-6288a',
    authDomain: 'to-do-app-6288a.firebaseapp.com',
    storageBucket: 'to-do-app-6288a.appspot.com',
    measurementId: 'G-YE09WWS2R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_sdUsojNA17kRCysBxrB3ZFRVs4bQE0',
    appId: '1:167961728502:android:935fbd96c0242165f2a3d7',
    messagingSenderId: '167961728502',
    projectId: 'to-do-app-6288a',
    storageBucket: 'to-do-app-6288a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALMu-RlleVExvDS9cQAnx1nIu7RkRQBFE',
    appId: '1:167961728502:ios:019b3bc441da409df2a3d7',
    messagingSenderId: '167961728502',
    projectId: 'to-do-app-6288a',
    storageBucket: 'to-do-app-6288a.appspot.com',
    iosClientId: '167961728502-1uu05dqiq0phsi268f7039shc6vblglc.apps.googleusercontent.com',
    iosBundleId: 'com.FlutterToDoApp.toDoIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALMu-RlleVExvDS9cQAnx1nIu7RkRQBFE',
    appId: '1:167961728502:ios:019b3bc441da409df2a3d7',
    messagingSenderId: '167961728502',
    projectId: 'to-do-app-6288a',
    storageBucket: 'to-do-app-6288a.appspot.com',
    iosClientId: '167961728502-1uu05dqiq0phsi268f7039shc6vblglc.apps.googleusercontent.com',
    iosBundleId: 'com.FlutterToDoApp.toDoIt',
  );
}
